# Generated by Django 5.2.8 on 2025-11-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='baths',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of bathrooms (e.g. 2.5)', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='beds',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Number of bedrooms', max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='hoa_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly HOA fee (if applicable)', max_digits=10, null=True),
        ),
    ]
