# Generated by Django 5.2.8 on 2025-11-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_baths_alter_listing_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='baths',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='beds',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='hoa_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
