# Generated by Django 5.2.8 on 2025-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_baths_alter_listing_beds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmahaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, help_text='Optional shorter blurb shown on the card. If left blank, the main description will be truncated.', max_length=255)),
                ('description', models.TextField(help_text='Longer description that can be shown on detail or external page.')),
                ('link', models.URLField(blank=True, help_text="Where the 'View resource' button should go (optional).", max_length=500, verbose_name='External link')),
                ('image', models.ImageField(blank=True, help_text='Photo or hero image for this Omaha resource.', null=True, upload_to='omaha_info/')),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Omaha info item',
                'verbose_name_plural': 'Omaha info items',
                'ordering': ('sort_order', 'title'),
            },
        ),
    ]
